name: The Sacred Elephant
favicon: null
layout_spectrum: 0.88729
typography_spectrum: 0.89884
title: Naturopathic Doctor California
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7dfec'
    - '#fdfbfc'
    - '#8e9293'
    - '#b0b1b3'
    - '#b188d8'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
