name: The Sacred Elephant
favicon: null
layout_spectrum: 0.8526081433519721
typography_spectrum: 0.7251038691028953
title: Naturopathic Doctor California
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7dfec'
    - '#fdfbfc'
    - '#8e9293'
    - '#b0b1b3'
    - '#b188d8'
  brandStrength: 0.9472015353385359
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
